name: dis18
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10
  - pandas
  - jupyter
  - streamlit
  - beautifulsoup4
  - lxml
  - pytest
  - spacy
  - geopy
  - transformers